-- Math: machine-checked formalizations of novel results from the monad research cluster.
-- Each module formalizes results first established informally in eliottcassidy2000/math.
-- Provenance for every theorem links back to its informal source (see each file's header).

import Math.Tournaments.Basic
import Math.Tournaments.OddCycleSpectrum
import Math.Tournaments.SmallMu
import Math.Tournaments.HamiltonianPaths
import Math.Tournaments.HamiltonianPathAutomorphism
import Math.Tournaments.Inshat
import Math.Tournaments.IndependencePolynomial
import Math.Tournaments.Jacobsthal
import Math.Tournaments.CyclotomicSeven
import Math.Tournaments.ForbiddenHSpectrum
import Math.Tournaments.Paley
import Math.Tournaments.CayleyBoost
import Math.Tournaments.Staircase
import Math.Tournaments.IntervalReversal
import Math.Tournaments.SelfConverse
import Math.FormalGroup.Basic
import Math.FormalGroup.NFoldSum
import Math.PathHomology.Basic
import Math.Krawtchouk.Basic
import Math.LonelyRunner.ApexCertificate
import Math.LonelyRunner.OwnerCongruence
import Math.LonelyRunner.SumFree
import Math.LonelyRunner.Fusion
import Math.LonelyRunner.FractalSumFree
import Math.LonelyRunner.DangerBlocks
import Math.LonelyRunner.UnitClock
import Math.LonelyRunner.DenominatorSieve
import Math.LonelyRunner.DoublingRigidity
import Math.LonelyRunner.DangerCount
import Math.LonelyRunner.CoveringDepth
import Math.LonelyRunner.UnitDistance
import Math.LonelyRunner.UnitDistanceCarrier
import Math.LonelyRunner.DepthGenerating
import Math.LonelyRunner.FlowShell
import Math.LonelyRunner.SignedSpeed
import Math.LonelyRunner.KrawtchoukNormalization
import Math.LonelyRunner.DelsarteLP
import Math.LonelyRunner.BalancedRelation
import Math.LonelyRunner.PairSumModulus
import Math.Collatz.Resonance
import Math.Collatz.Parity
import Math.IteratedLog.Altitude
import Math.Transcendence.SumProduct
import Math.NumberTheory.GoldbachLemoine
import Math.NumberTheory.PerfectMersenne
import Math.NumberTheory.KnacciMersenne
import Math.NumberTheory.InvolutionModulus
import Math.NumberTheory.FibonacciProduct
import Math.SetTheory.ContinuumHypothesisCarrier
import Math.Foundations.RecursiveFourthFace
import Math.Moser.LayeredSlabs
import Math.Combinatorics.ChromaticTieInduction
import Math.Combinatorics.HadwigerNelsonBridge
import Math.Combinatorics.AlternatingGroupGraph
import Math.Polynomial.RootCount
import Math.Combinatorics.HexagonalSevenColoring
import Math.Tournaments.PaleyRado
import Math.LonelyRunner.HalfTurnParity
import Math.LonelyRunner.SevenClockFiber
import Math.UnitDistance.EisensteinNeighbors
import Math.UnitDistance.ChordSpectrum
import Math.UnitDistance.DeletionLadder
import Math.Galois.CommutatorDepth
import Math.Tournaments.AutOddOrder
import Math.Combinatorics.PochhammerSign
import Math.Tournaments.SkewDiscriminant
import Math.Tournaments.PfaffianParity
import Math.Tournaments.SwitchingDeterminant
import Math.LonelyRunner.Friendliness
import Math.LonelyRunner.LonelyFourteen
import Math.LonelyRunner.LonelyNineteen
import Math.LonelyRunner.SingularSeries
import Math.NumberTheory.HeegnerNineteen
import Math.NumberTheory.GeneralBaseQRCongruence
import Math.Combinatorics.InclusionExclusionTriangle
import Math.Combinatorics.Cochromatic
import Math.Combinatorics.CochromaticBound
import Math.Combinatorics.InvolutionAverage
import Math.Combinatorics.DelannoyIdentity
import Math.Combinatorics.FibbinaryMoserCarrier
import Math.Tournaments.HalfTiling
