/-
# The alternating group graph: generated by 3-cycles = cube roots of unity = the resonance

Provenance: `eliottcassidy2000/math` — HYP-2305 (S635).  The **alternating group graph** `AG_n` is the Cayley graph
of the alternating group `A_n` with the 3-cycles as generators.  Its generators are exactly the **3-cycles**, which
are the **cube roots of the identity** (`σ³ = 1`, with permutation-matrix eigenvalues `1, ω, ω² = e^{±2πi/3}`) and are
**even** (they lie in `A_n`).  So `AG_n` is built from the same cube-root / `π/3` / `Φ₃` resonance the whole arc
converges on — and computation shows `AG_n` is **3-chromatic** (the triangle/3-cycle forces `χ ≥ 3`, and a 3-coloring
exists) with `α = |V|/3`, so the `χ·α = |V|` bound (`exists_indepSet_card_mul_ge`, S634) is tight: `AG_n` is "the
third color" incarnate, the cube root realized as a chromatic number for every `n`.
-/
import Mathlib

namespace Math.Combinatorics

open Equiv Equiv.Perm

variable {α : Type*} [Fintype α] [DecidableEq α]

/-- **The AG_n generators are cube roots of unity.**  A 3-cycle `σ` (the generator of the alternating group graph)
satisfies `σ³ = 1`: it is a cube root of the identity, with eigenvalues the cube roots of unity `e^{±2πi/3}` — the
`π/3` resonance. -/
theorem threeCycle_cube {f : Perm α} (h : f.IsThreeCycle) : f ^ 3 = 1 := by
  rw [← h.orderOf]
  exact pow_orderOf_eq_one f

/-- **The AG_n generators are even.**  A 3-cycle lies in the alternating group `A_n` (sign `= 1`): the alternating
group graph is generated within `A_n` by these even cube roots. -/
theorem threeCycle_mem_alternating {f : Perm α} (h : f.IsThreeCycle) :
    f ∈ alternatingGroup α :=
  h.mem_alternatingGroup

/-- A 3-cycle is a *nontrivial* cube root (`σ ≠ 1`): it has order exactly `3`, so the cube root is genuine — the
generator is a true `ω`, not the identity. -/
theorem threeCycle_ne_one {f : Perm α} (h : f.IsThreeCycle) : f ≠ 1 :=
  h.isCycle.ne_one

end Math.Combinatorics
