/-
# Self-converse tournaments and the perspective flip

Provenance: `eliottcassidy2000/math` -
`01-canon/theorems/THM-409-self-converse-perspective-flip-involution.md`.

This file formalizes the algebraic core of THM-409.  Anti-automorphisms of a
tournament are exactly the isomorphisms to the converse tournament; once one exists,
they form both a left and a right coset of the automorphism group.  Consequently every
anti-automorphism induces the same involution on the quotient of vertices by
automorphism orbit.
-/
import Math.Tournaments.Basic

namespace Math.Tournaments

/-- A permutation preserving all tournament arcs. -/
def IsAutomorphism {V : Type*} (T : Tournament V) (σ : Equiv.Perm V) : Prop :=
  ∀ x y, T.beats x y ↔ T.beats (σ x) (σ y)

/-- A permutation reversing all tournament arcs, equivalently an isomorphism to the
converse tournament. -/
def IsAntiAutomorphism {V : Type*} (T : Tournament V) (σ : Equiv.Perm V) : Prop :=
  ∀ x y, T.beats x y ↔ T.beats (σ y) (σ x)

namespace IsAutomorphism

variable {V : Type*} {T : Tournament V} {σ τ : Equiv.Perm V}

/-- The identity permutation is a tournament automorphism. -/
theorem refl : IsAutomorphism T 1 := by
  intro x y
  rfl

/-- Automorphisms are closed under composition. -/
theorem mul (hσ : IsAutomorphism T σ) (hτ : IsAutomorphism T τ) :
    IsAutomorphism T (σ * τ) := by
  intro x y
  calc
    T.beats x y ↔ T.beats (τ x) (τ y) := hτ x y
    _ ↔ T.beats (σ (τ x)) (σ (τ y)) := hσ (τ x) (τ y)
    _ ↔ T.beats ((σ * τ) x) ((σ * τ) y) := by simp

/-- The inverse of an automorphism is an automorphism. -/
theorem inv (hσ : IsAutomorphism T σ) : IsAutomorphism T σ⁻¹ := by
  intro x y
  specialize hσ (σ⁻¹ x) (σ⁻¹ y)
  simpa using hσ.symm

end IsAutomorphism

namespace IsAntiAutomorphism

variable {V : Type*} {T : Tournament V} {σ τ α : Equiv.Perm V}

/-- The inverse of an anti-automorphism is an anti-automorphism. -/
theorem inv (hσ : IsAntiAutomorphism T σ) : IsAntiAutomorphism T σ⁻¹ := by
  intro x y
  specialize hσ (σ⁻¹ y) (σ⁻¹ x)
  simpa [and_comm] using hσ.symm

/-- Left multiplication by an automorphism preserves anti-automorphisms. -/
theorem automorphism_mul (hα : IsAutomorphism T α) (hσ : IsAntiAutomorphism T σ) :
    IsAntiAutomorphism T (α * σ) := by
  intro x y
  calc
    T.beats x y ↔ T.beats (σ y) (σ x) := hσ x y
    _ ↔ T.beats (α (σ y)) (α (σ x)) := hα (σ y) (σ x)
    _ ↔ T.beats ((α * σ) y) ((α * σ) x) := by simp

/-- Right multiplication by an automorphism preserves anti-automorphisms. -/
theorem mul_automorphism (hσ : IsAntiAutomorphism T σ) (hα : IsAutomorphism T α) :
    IsAntiAutomorphism T (σ * α) := by
  intro x y
  calc
    T.beats x y ↔ T.beats (α x) (α y) := hα x y
    _ ↔ T.beats (σ (α y)) (σ (α x)) := hσ (α x) (α y)
    _ ↔ T.beats ((σ * α) y) ((σ * α) x) := by simp

/-- The product of two anti-automorphisms is an automorphism. -/
theorem mul (hσ : IsAntiAutomorphism T σ) (hτ : IsAntiAutomorphism T τ) :
    IsAutomorphism T (σ * τ) := by
  intro x y
  calc
    T.beats x y ↔ T.beats (τ y) (τ x) := hτ x y
    _ ↔ T.beats (σ (τ x)) (σ (τ y)) := hσ (τ y) (τ x)
    _ ↔ T.beats ((σ * τ) x) ((σ * τ) y) := by simp

end IsAntiAutomorphism

variable {V : Type*} (T : Tournament V)

/-- The automorphism orbit relation on vertices. -/
def SameAutomorphismOrbit (x y : V) : Prop :=
  ∃ σ : Equiv.Perm V, IsAutomorphism T σ ∧ σ x = y

/-- The setoid of rooted perspectives: two roots are equivalent when an automorphism
of the tournament carries one to the other. -/
def automorphismOrbitSetoid : Setoid V where
  r := SameAutomorphismOrbit T
  iseqv := by
    refine ⟨?refl, ?symm, ?trans⟩
    · intro x
      exact ⟨1, IsAutomorphism.refl, rfl⟩
    · intro x y hxy
      rcases hxy with ⟨σ, hσ, rfl⟩
      exact ⟨σ⁻¹, hσ.inv, by simp⟩
    · intro x y z hxy hyz
      rcases hxy with ⟨σ, hσ, rfl⟩
      rcases hyz with ⟨τ, hτ, hτ_eq⟩
      exact ⟨τ * σ, hτ.mul hσ, by simp [hτ_eq]⟩

/-- Rooted perspectives of a tournament, i.e. automorphism orbits of vertices. -/
def RootedPerspective : Type _ :=
  Quot (automorphismOrbitSetoid T)

/-- The anti-automorphisms of a self-converse tournament form the left coset of the
automorphism group generated by any chosen anti-automorphism. -/
theorem antiAutomorphisms_eq_left_coset {σ : Equiv.Perm V}
    (hσ : IsAntiAutomorphism T σ) :
    {τ : Equiv.Perm V | IsAntiAutomorphism T τ} =
      {τ : Equiv.Perm V | ∃ α : Equiv.Perm V, IsAutomorphism T α ∧ τ = α * σ} := by
  ext τ
  constructor
  · intro hτ
    refine ⟨τ * σ⁻¹, hτ.mul hσ.inv, ?_⟩
    simp [mul_assoc]
  · intro hτ
    rcases hτ with ⟨α, hα, rfl⟩
    exact IsAntiAutomorphism.automorphism_mul hα hσ

/-- The anti-automorphisms of a self-converse tournament form the right coset of the
automorphism group generated by any chosen anti-automorphism. -/
theorem antiAutomorphisms_eq_right_coset {σ : Equiv.Perm V}
    (hσ : IsAntiAutomorphism T σ) :
    {τ : Equiv.Perm V | IsAntiAutomorphism T τ} =
      {τ : Equiv.Perm V | ∃ α : Equiv.Perm V, IsAutomorphism T α ∧ τ = σ * α} := by
  ext τ
  constructor
  · intro hτ
    refine ⟨σ⁻¹ * τ, hσ.inv.mul hτ, ?_⟩
    simp
  · intro hτ
    rcases hτ with ⟨α, hα, rfl⟩
    exact hσ.mul_automorphism hα

/-- The square of an anti-automorphism is an automorphism. -/
theorem antiAutomorphism_square_isAutomorphism {σ : Equiv.Perm V}
    (hσ : IsAntiAutomorphism T σ) : IsAutomorphism T (σ * σ) :=
  hσ.mul hσ

/-- Conjugating an automorphism by an anti-automorphism gives another automorphism. -/
theorem anti_conj_automorphism {σ α : Equiv.Perm V}
    (hσ : IsAntiAutomorphism T σ) (hα : IsAutomorphism T α) :
    IsAutomorphism T (σ * α * σ⁻¹) :=
  (hσ.mul_automorphism hα).mul hσ.inv

/-- An anti-automorphism sends automorphism-equivalent vertices to
automorphism-equivalent vertices. -/
theorem anti_preserves_sameAutomorphismOrbit {σ : Equiv.Perm V}
    (hσ : IsAntiAutomorphism T σ) {x y : V} :
    SameAutomorphismOrbit T x y → SameAutomorphismOrbit T (σ x) (σ y) := by
  intro hxy
  rcases hxy with ⟨α, hα, hαx⟩
  refine ⟨σ * α * σ⁻¹, anti_conj_automorphism T hσ hα, ?_⟩
  simp [mul_assoc, hαx]

/-- The map on rooted perspectives induced by an anti-automorphism. -/
def antiPerspectiveMap (σ : Equiv.Perm V) (hσ : IsAntiAutomorphism T σ) :
    RootedPerspective T → RootedPerspective T :=
  Quot.map σ fun _ _ hxy => anti_preserves_sameAutomorphismOrbit T hσ hxy

/-- Any two anti-automorphisms induce the same map on rooted perspectives. -/
theorem antiPerspectiveMap_eq {σ τ : Equiv.Perm V}
    (hσ : IsAntiAutomorphism T σ) (hτ : IsAntiAutomorphism T τ) :
    antiPerspectiveMap T σ hσ = antiPerspectiveMap T τ hτ := by
  funext q
  refine Quot.induction_on q ?_
  intro x
  apply Quot.sound
  exact ⟨τ * σ⁻¹, hτ.mul hσ.inv, by simp⟩

/-- The perspective map induced by any anti-automorphism is an involution. -/
theorem antiPerspectiveMap_involutive {σ : Equiv.Perm V}
    (hσ : IsAntiAutomorphism T σ) :
    Function.Involutive (antiPerspectiveMap T σ hσ) := by
  intro q
  refine Quot.induction_on q ?_
  intro x
  apply Quot.sound
  exact ⟨(σ * σ)⁻¹, (antiAutomorphism_square_isAutomorphism T hσ).inv, by simp⟩

end Math.Tournaments
